service: golf-handicap-calculator

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  profile: Madushan
  region: us-east-2
  stage: dev # default stage, for multi stage deployment use ${opt:stage, 'dev'}
  versionFunctions: false
  tags:
    environment: ${self:provider.stage}
    project: golf

  environment:
    #airTable
    AIRTABLE_API_KEY: ${file(./secrets.env.yml):airTable.AIRTABLE_API_KEY}
    AIRTABLE_BASE_KEY: ${file(./secrets.env.yml):airTable.AIRTABLE_BASE_KEY}
    TBL_ROUNDS: ${file(./secrets.env.yml):airTable.TBL_ROUNDS}

functions:
  # getting all rounds from airtable
  getRounds:
    handler: lambdas/endpoints/getRounds.handler
    description: Getting all entered rounds from airtable
    layers:
      - arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p38-requests:6
